apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: gitops-staging
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:6KawwzrJO+5Oc7GsGF69u1txsvVCLecvwli2Ai154an6CmvBBZjyy6Fx0ARoBl9dXnxzKke2XvIkBxi4uLSqQ7O0tYTu1HXviY1/,iv:L0ayGpn+d7PkaKuQLj2F6ckyc3fsUQdLnShHYzUam3Q=,tag:NyLbakVgucqvJ12FGB42yQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:nDWacndR+9PBwwmkY5xlbUSwSdl8YC5TFMdI/jAKv00V4ZzYUMt8AlIBQ9U=,iv:a/021WmgBOktaFFeoqfbdn/rI9hqm8YU8YitEz+iFEY=,tag:+gg0HWpgGDO8AHJHHSpG/Q==,type:str]
    API_SIGNING_KEY: ENC[AES256_GCM,data:6A4gBbt7XwuRMAVfOH5Ih3k+IZU8OQFPWfka,iv:+ujdZ0Ec6HlRuAM2F+J6zmNUXV6bdkB/c0KyeeR8TWk=,tag:EhbaeDPnoEeU0c2IbSZcmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12grd73m55hkylvnx7nm5vf4snn8usnp8kelwv89z7zwazng0s52qrjjr27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBselRUNm5hOTdmT2lkQ0R6
            RlgyajNUMkI2MlNXYzlmV3FDS2g0bVN6N1ZJCldhWENHQTBvVnY3SUJYc1MvRXA5
            ZzdGdlU4T1ZIcFhYOUhwN2tIdUpnSlkKLS0tIEk3QVNXUUJud2QxMzZTckVERHNB
            cXRkVTdER1E1L3FLMDg0a3RQZ3MvbjgK6uPnBDeqBC1YB3aZUwtWwrvEqWEZ66zg
            xNkjo6iQBT0j33YWnWskZj7tNzdIpDnVJiiFs0mSS1GVfIFrkcXd9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T15:10:59Z"
    mac: ENC[AES256_GCM,data:dBPJvnFAC6nO5W3h8ve6mE6MAnuu2g2pRA33Tdxcr5JdKgFUznBr7YNs0s2I+5smMi2oi3D4aExs38+y8qsiRT8pJXDdQCT9AKwbcW48oHJdhpSiUZ2RB7SPJrA5WFGyJHZp/wZnmmIBmt1jZBb6lbDMpozYvB28xVJuqpH3fiQ=,iv:LHyUVQjkh48F6839nUQUkzANuSPj9fK0KK5sQwVhpOk=,tag:1OJd49wgh8R+vXkINufYJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
