apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: gitops-staging
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yz0bb9pk2mPAYeugSK6ifcbcDa2umMh/Rpyyon6zzJc+9Z0PkXAd+9EL98U=,iv:gtctm/HUWy4BgwDHeI86+qtwpj5k/vxKs/9WOUXKB/0=,tag:ooDCmE/Q0FMBQmjVdHyc0Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:SkxyT+hY7sFA5Qc1T/eo4aQFWrI=,iv:wzPreYj/qQoT5cwns2wyHcANOxNIJb6QDD6XP2V3sm0=,tag:KpVVyBjVEEMV1A6fVmRNsg==,type:str]
    API_SIGNING_KEY: ENC[AES256_GCM,data:m/gGFysTgbneOGdC9WkHepiQzmdrzkC63Ysj,iv:4xICDyScSKqwTKgIYzpbYbbQ8K/iiKOKwpFuARyPwdU=,tag:zGj69KeqAApW5iRuyJWqGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUVZOYWp4VVZnTDMrS2Rv
            VVFFNjJQR3ZkNmhXaEFYVm42TXJSVkFNSUVFCnJmMWRjbVlScDYwVSt5WnFWbTRt
            RUM3UHlzenFZUW5YbStSL2xySk12aFkKLS0tIGIycDJKdkE1QnJUZUJnT3EvbHVV
            YmE1RFNWSFFobjRSZmxNZGV2d3NId0kKsGRa8FFA2ORooQmH9ovMZkIAocn/H4VL
            SOu/0AoOYd4q27INv0gTJHWPfF4ijduSVtU97fmPsUbOQUpAXYo0Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h3z0hwp4rrwfhjllw2u57h29ulgkfkg7t8dg63hna69rukkxwvas7vdfl8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T15:40:53Z"
    mac: ENC[AES256_GCM,data:p66n4xWV9+dVFdc3MHnGQESKyvDBRZcOPb8oNCtyR3r8e338l1fXsLGR8Gwz0cmJkmQMgmqD7u5JzHsAVoVa1vItbUVA8jAaGUgIK31tX0U1wiC6rIcU981wzVwQqI6C20Vr1Wh4r+6+c6RbetngaNvHLyLsOUuWaBOhi8DXypE=,iv:9DRESMjsUIXvx1sl0fC07KauNGQbpeiJBUvHVWXKL78=,tag:YAZaPnUd1csKu+BSs5cr7Q==,type:str]
    version: 3.13.3
